### ISSUE TITLE
Add it for GitHub readme profiles

### ISSUE THREAD

**Issue by rushabh-v** [rushabh-v/Show-Your-Contributions#3]
The webpage this action creates will be containing all the issues and PRs opened by a user. Which might be a long list for some users. As GitHub profile readmes should be shorter, adding only PRs with a threshold would be a good idea. (If `threshold = 5` it should only add the list of orgs/repos where a particular user has more than or equal to 5 PRs.)

**Comment by athuljayaraj** [comment]
I've done some dirty coding to get this done. 
Please check this script: `https://github.com/athuljayaraj/Show-Your-Contributions/blob/f-set-pr-threshold/generate_doc.py`

There's more to be done. README needs an update(to include threshold). Also, we could take out the hardcoded htmls from py files, and instead have html template in place.

**Comment by rushabh-v** [comment]
Hey @athuljayaraj, Thanks for working on this.

The changes you have made look good. Please open a PR and we can work together to get it done.

> Also, we could take out the hardcoded htmls from py files, and instead have html template in place.

Yes, there was a reason because of which I put it inside py files. But that reason doesn't exist anymore. So maybe after adding this feature we can work on cleaning that up a bit. (by templates you mean creating a file that contains HTML code and using that in py files or something else?)

**Comment by athuljayaraj** [comment]
I meant the same @rushabh-v 

I've opened a PR for this, but the README update isn't done yet. Please help me out with that one. The idea is to read `THRESHOLD` as the second argument.

```name: update-my-contributions
on:
  schedule:
   - cron: "0 0 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Get Updates
        env:
          THRESHOLD: 2
        run: |
          sudo apt install python3-setuptools
          git clone https://github.com/rushabh-v/Show-Your-Contributions
          cp -r ./Show-Your-Contributions/* ./
          pip3 install pygithub
          echo $THRESHOLD
          python3 fetch_contribs.py ${{ secrets.GIT_TOKEN }}
          python3 generate_doc.py ${{ secrets.GIT_TOKEN }} $THRESHOLD
      - name: Commit
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            contributions.html
            total_contribs
          commit-msg: Update resources
          github-token: ${{ secrets.GIT_TOKEN }}
```

Will this work? I couldn't test since the previous script itself fails for me.

**Comment by rushabh-v** [comment]
What problem are you facing with the current script?

**Comment by shubhamcodez** [comment]
Hey guys, Are you still working on this ?

**Comment by rushabh-v** [comment]
Yes, refer to https://github.com/rushabh-v/Show-Your-Contributions/pull/5
