### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by avinashkranjan** [rushabh-v/Show-Your-Contributions#4]
**Error**

File "fetch_contribs.py", line 39, in creat_json
    my_contribs[repo_name]['lang'] = list(r.get_languages().keys())[0]
IndexError: list index out of range

![chrome_PtOrHMJkjK](https://user-images.githubusercontent.com/55796944/95565769-4530ac80-0a3e-11eb-8385-5e4f508b29e0.png)

**Comment by rushabh-v** [comment]
Thanks for reporting it!
The reason should be that a particular repo might not have any languages (for example [this](https://github.com/rushabh-v/rushabh-v)) and in that case, there will be this error.

Will commit shortly!

**Comment by rushabh-v** [comment]
@avinashkranjan, I have fixed the issue with https://github.com/rushabh-v/Show-Your-Contributions/commit/a509c3c7ee365c0631a05b7b9a5f58ece9a29570. You can wait for 00:00 UTC, or you can go to the failed workflow and `Re-run jobs` to have the HTML doc generated now. Please tell me if you still face any problem.

Thanks!

**Comment by avinashkranjan** [comment]
@rushabh-v works like a charm....Thanks..
