### ISSUE TITLE
Add more language-color pairs in colors.json

### ISSUE THREAD

**Issue by rushabh-v** [rushabh-v/Show-Your-Contributions#8]
Add language to color mapping with colors that GitHub uses to represent different languages.

**Comment by manav13** [comment]
Hi Rushabh,
Take a look at this repo. [Link](https://github.com/doda/github-language-colors)

If you feel this is correct, then I can write a script to convert from Hex codes to RGB codes and then add it to colors.json file

**Comment by rushabh-v** [comment]
Hi Manav,

Thanks for taking a look.

Yes, it looks good. Feel free to send a PR.

I would also suggest replacing any existing RGB values if they differ from the the once in the repo that you mentioned.

Thank you!

**Comment by manav13** [comment]
Yeah sure, will correct existing RGB values.

**Comment by manav13** [comment]
Hey just clearing a doubt here.
You have used ``` "GitHub": "rgb(12, 12, 9)" ``` as default case, right?
With Default case, I mean when a language-color mapping is not found.

**Comment by rushabh-v** [comment]
Yes. And it also works when a repo doesn't contain any language. (e.g., a repo with only markdowns or txt files)

**Comment by manav13** [comment]
Got it, Thanks for the clarification!
Loved contributing to your project.
